config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks' }, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'}

  get 'pages/terms'
  get 'pages/privacy'
  get 'pages/payments'
  get 'pages/about'
  get '/myprojects' => 'project#list'
  get '/pricing' => 'pages#pricing'
  post '/update_card' => 'plan_subscriptions#update_card'
  post '/subscribe' => 'project#subscribe'
  get '/blog' => 'post#index'

  get '/next' => 'task#show_next'
  get '/prev' => 'task#show_prev'

  match '/complete', to: 'completed_task#complete', via: :post
  match '/uncomplete', to: 'completed_task#uncomplete', via: :delete

  root 'project#index'

  resources :project do
    resources :task, only: [:show, :show_next, :show_prev]
  end

  resources :project do
    resources :project_stacks, only: [:show]
  end

  resources :project do
    resources :preview_videos, only: [:show]
  end

  resources :project do
    resources :reviews, only: [:create, :destroy]
  end

  resource :plan_subscriptions
  resources :post
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/plan_subscription.rb
class PlanSubscription < ApplicationRecord
  belongs_to :user
  accepts_nested_attributes_for :user
end

app/controllers/plan_subscriptions_controller.rb
class PlanSubscriptionsController < ApplicationController
  before_action :authenticate_user!
  def new
    @plan = params[:plan]
  end

  def create
    customer = if current_user.stripe_user_id?
                 Stripe::Customer.retrieve(current_user.stripe_user_id)
               else
                 Stripe::Customer.create(
                   :email => current_user.email,
                   :source => params[:stripeToken]
                 )
               end
    subscription = customer.subscriptions.create(
      plan: params[:plan] + params[:plan_period]
    )
    options = {
      stripe_user_id: customer.id,
      stripe_subscription_id: subscription.id,
      plan: params[:plan],
    }
    current_user.update(options)
    subscription = PlanSubscription.create user_id: current_user.id
    redirect_to root_path, notice: "Подписка оформлена успешно"
    #UserMailer.welcome_email(current_user.id).deliver

  end

  def update
    @plan = params[:plan]
  end

  def destroy
    customer = Stripe::Customer.retrieve(current_user.stripe_user_id)
    subscription = Stripe::Subscription.retrieve(current_user.stripe_subscription_id)
    subscription.delete()
    subscription = PlanSubscription.where(:user_id == current_user.id).delete_all
    current_user.update(stripe_subscription_id: nil)
    @plan = params[:plan]
    current_user.update(plan: 'free')
    user = current_user
    redirect_to root_path, notice: "Подписка отменена"
  end

  def update_card

    customer = Stripe::Customer.retrieve(current_user.stripe_user_id)
    customer.source = params[:stripeToken]
    customer.save
    redirect_to edit_user_registration_path, notice: "Данные банковской карты обновлены"
  end

end

app/helpers/plan_subscriptions_helper.rb
module PlanSubscriptionsHelper
end

app/views/plan_subscriptions/new.html.erb
<div class="credit-card" data-turbolinks="false">
  <div class="row">
    <div class="col-lg-offset-2 col-lg-8 col-md-offset-1 col-md-10">
      <h1 class="text-center">Начните занятия сегодня!</h1>
      <h4 class="text-center">(Вы можете отменить подписку в любое время)</h4>
      <br>
      <div class="panel panel-c4s">
        <div class="panel-heading">
          <h1 class="panel-title text-center">Оплата</h1>
        </div>
        <div class="panel-body text-center">
          <script src="https://js.stripe.com/v3/"></script>
          <div class="stripe-form">
            <%= form_for plan_subscriptions_path, url: {action: 'create', method: 'post'}, html: {class: 'c4s-form', id: 'payment-form'} do |form| %>
              <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
              <%= hidden_field_tag :plan, @plan %>
              <div class="row">
                <div class="col-lg-offset-2 col-lg-4 col-md-offset-2 col-md-4 col-sm-offset-2 col-sm-4">
                  <div class="c4s-radio">
                    <input id="monthly" type="radio" name="plan_period" value="_monthly" checked="checked">
                    <label for="monthly"><span>Ежемесячно <span class="price">- <% if @plan == 'standart' %>2 500<% else %>5 000<% end %> руб.</span></span></label>
                  </div>
                </div>
                <div class="col-lg-5 col-md-5 col-sm-5">
                  <div class="c4s-radio">
                    <input type="radio" name="plan_period" value="_annual" id="annual">
                    <label for="annual"><span>Ежегодно <span>- <% if @plan == 'standart' %>25 000<% else %>50 000<% end %> руб.</span></span><span class="label label-default">2 месяца бесплатно</span></label>
                  </div>
                </div>
              </div>

              <div class="group">
                <label><div class="field" id="card-element"></div></label>
                <br>
                <p class="text-with-highlight">Нажимая на кнопку "Начать обучение", вы соглашаетесь с <%= link_to "Условиями обслуживания", pages_terms_path, class: "text-red" %></p>
                <button type="submit" id="btn_pay">Начать обучение</button>
              </div>

              <div class="outcome">
                <div class="error">

                </div>
              </div>

            <% end %>
          </div>
          <script type="text/javascript">

          var stripe = Stripe('<%= Rails.configuration.stripe[:publishable_key]%>');

          var elements = stripe.elements();
          var btn_pay = document.getElementById('btn_pay');

          var card = elements.create('card', {
            hidePostalCode: true,
            style: {
              base: {
                iconColor: '#666EE8',
                color: '#31325F',
                lineHeight: '40px',
                fontWeight: 300,
                fontFamily: 'Helvetica Neue',
                fontSize: '15px',

                '::placeholder': {
                  color: '#CFD7E0',
                },
              },
            }
          });
          card.mount('#card-element');

          function setOutcome(result) {
            var errorElement = document.querySelector('.error');
            errorElement.classList.remove('visible');

            if (result.token) {
              // Send the token to your server.
              stripeTokenHandler(result.token);
            } else if (result.error) {
              btn_pay.removeAttribute('disabled');
              btn_pay.innerHTML = "Начать обучение"
              errorElement.textContent = result.error.message;
              errorElement.classList.add('visible');
            }
          }

          card.on('change', function(event) {
            setOutcome(event);
          });

          // Handle form submission.
          var form = document.getElementById('payment-form');
          form.addEventListener('submit', function(event) {
            event.preventDefault();
            btn_pay.setAttribute('disabled', 'true');
            btn_pay.innerHTML = "<i class='fa fa-spinner fa-spin fa-1x' style='color:white;'></i> Обработка...";
            stripe.createToken(card).then(setOutcome);
          });

          // Send the token to your server.
          function stripeTokenHandler(token) {
            // Insert the token ID into the form so it gets submitted to the server
            var form = document.getElementById('payment-form');
            var hiddenInput = document.createElement('input');
            hiddenInput.setAttribute('type', 'hidden');
            hiddenInput.setAttribute('name', 'stripeToken');
            hiddenInput.setAttribute('value', token.id);
            form.appendChild(hiddenInput);

            // Submit the form
            form.submit();
          }

          </script>
        </div>
      </div>
    </div>
  </div>
</div>