config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks' }, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'}

  get 'pages/terms'
  get 'pages/privacy'
  get 'pages/payments'
  get 'pages/about'
  get '/myprojects' => 'project#list'
  get '/pricing' => 'pages#pricing'
  post '/update_card' => 'plan_subscriptions#update_card'
  post '/subscribe' => 'project#subscribe'
  get '/blog' => 'post#index'

  get '/next' => 'task#show_next'
  get '/prev' => 'task#show_prev'

  match '/complete', to: 'completed_task#complete', via: :post
  match '/uncomplete', to: 'completed_task#uncomplete', via: :delete

  root 'project#index'

  resources :project do
    resources :task, only: [:show, :show_next, :show_prev]
  end

  resources :project do
    resources :project_stacks, only: [:show]
  end

  resources :project do
    resources :preview_videos, only: [:show]
  end

  resources :project do
    resources :reviews, only: [:create, :destroy]
  end

  resource :plan_subscriptions
  resources :post
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/completed_task.rb
class CompletedTask < ApplicationRecord
  belongs_to :task
  belongs_to :user
end

app/controllers/completed_task_controller.rb
class CompletedTaskController < ApplicationController
  respond_to :js
  def complete
    @user = current_user
    @task = Task.find(params[:task_id])
    @project = Project.find(@task.project_id)
    @user.complete!(@task)
        respond_to do |format|
          format.html { redirect_to :back }
          format.js { render layout: false }
      end
  end

  def uncomplete
    #@completed_task = CompletedTask.where(":task_id == params[:task_id] and :user_id == current_user.id")
    @user = current_user
    @task = Task.find(params[:task_id])
    @project = Project.find(@task.project_id)
    @completed_task = @user.completed_tasks.find_by_task_id(params[:task_id])
    @completed_task.destroy
        respond_to do |format|
          format.html { redirect_to :back }
          format.js { render layout: false }
      end
  end
end

app/views/completed_task/_button.html.erb
<% if user_signed_in? %>
  <% if current_user.completed?(task) %>
    <%= link_to uncomplete_path(task_id: task.id), data: {disable_with: "<i class='fa fa-spinner fa-spin fa-1x' style='font-size: 16px; color:#28B62C;'></i>", remote: true, method: "delete"}, rel: "nofollow" do %>
      <i class="fa fa-incompleted fa-check-circle fa-lg"></i>
    <% end %>
  <% else %>
    <%= link_to complete_path(task_id: task.id), data: {disable_with: "<i class='fa fa-spinner fa-spin fa-1x' style='font-size: 16px; color:#28B62C;'></i>", remote: true, method: "post"}, rel: "nofollow" do %>
      <i class="fa fa-completed fa-check-circle fa-lg"></i>
    <% end %>
  <% end %>
<% else %>
  <i class="fa fa-incompleted fa-check-circle fa-lg"></i>
<% end %>

app/views/completed_task/complete.js.erb
$('span#task_complete_button_<%= @task.id %>').html('<%= j render partial: "button", locals: {task: @task} %>');
$('span#task_complete_button_<%= @task.id %>').parent().parent().attr("class", "list-group-item task-completed");
$('#user_progress').html('<% if current_user.completed_tasks.count > 0 %><%= current_user.completed_tasks.count %><% else %>0<% end %>');
$('.bar__completed').css('width', '<%= (current_user.completed_tasks.count.to_f / @project.tasks.where("header <> '1'").count.to_f * 100).round(2) %>%');

app/views/completed_task/uncomplete.js.erb
$('span#task_complete_button_<%= @task.id %>').html('<%= j render partial: "button", locals: {task: @task} %>');
$('span#task_complete_button_<%= @task.id %>').parent().parent().removeClass("task-completed");
$('#user_progress').html('<% if current_user.completed_tasks.count > 0 %><%= current_user.completed_tasks.count %><% else %>0<% end %>');
$('.bar__completed').css('width', '<%= (current_user.completed_tasks.count.to_f / @project.tasks.where("header <> '1'").count.to_f * 100).round(2) %>%');