config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks' }, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'}

  get 'pages/terms'
  get 'pages/privacy'
  get 'pages/payments'
  get 'pages/about'
  get '/myprojects' => 'project#list'
  get '/pricing' => 'pages#pricing'
  post '/update_card' => 'plan_subscriptions#update_card'
  post '/subscribe' => 'project#subscribe'
  get '/blog' => 'post#index'

  get '/next' => 'task#show_next'
  get '/prev' => 'task#show_prev'

  match '/complete', to: 'completed_task#complete', via: :post
  match '/uncomplete', to: 'completed_task#uncomplete', via: :delete

  root 'project#index'

  resources :project do
    resources :task, only: [:show, :show_next, :show_prev]
  end

  resources :project do
    resources :project_stacks, only: [:show]
  end

  resources :project do
    resources :preview_videos, only: [:show]
  end

  resources :project do
    resources :reviews, only: [:create, :destroy]
  end

  resource :plan_subscriptions
  resources :post
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/task.rb
class Task < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: [:slugged, :finders]

  belongs_to :project
  has_many :completed_tasks

  validates :title, presence: true, length: {maximum: 80}
  validates :project, presence: true

  def next
    project.tasks.where("tag > ? AND header = ?", tag, false).order(:tag).first
  end

  def prev
    project.tasks.where("tag < ? AND header = ?", tag, false).order(:tag).last
  end
end

app/controllers/task_controller.rb
class TaskController < ApplicationController
  before_action :authenticate_user!
  def show
    project = Project.find(params[:project_id])
    @tasks = project.tasks.order(:tag)

    joined = false

    if !current_user.nil? && !current_user.projects.nil?
      joined = current_user.projects.include?(project)
    end

    if !current_user.nil?

      if project.pricing_type == 'free'
        if joined

          @task = @tasks.find(params[:id])

          @next_task = @task.next
          @prev_task = @task.prev
        else
          flash[:notice] = "Ошибка доступа"
          redirect_to project
        end
      else
        if current_user.plan == 'free'
          redirect_to pricing_path, alert: "Приобретите подписку для доступа к этому проекту"
        else
          plan_subscription = PlanSubscription.find_by(user_id: current_user.id)
          allowedprojects = (((Time.current - plan_subscription.updated_at)/1.day).round)/30+1
          if (current_user.plan == 'standart' && current_user.projects.where("pricing_type == 'pro'").count > allowedprojects)
            redirect_to pricing_path, alert: "Улучшите тарифный план для доступа к этому проекту. Сейчас вам доступно "+allowedprojects.to_s+" проектов"
          else
            if joined

              @task = @tasks.find(params[:id])

              @next_task = @task.next
              @prev_task = @task.prev
            else
              flash[:notice] = "Ошибка доступа"
              redirect_to project
            end
          end
        end
      end

    end
  end

  def show_next
    @task = Task.find(params[:id])
    @project = Project.find(@task.project_id)
    joined = false

    if !current_user.nil? && !current_user.projects.nil?
      joined = current_user.projects.include?(@project)
    end

    if joined
      @next_task = @task.next
      @prev_task = @task.prev
      if current_user.completed?(@task)
        redirect_to [@next_task.project, @next_task]
      else
        current_user.complete!(@task)
        redirect_to [@next_task.project, @next_task]
      end
    else
      flash[:notice] = "Ошибка доступа"
      redirect_to @project
    end
  end

  def show_prev
    @task = Task.find(params[:id])
    @project = Project.find(@task.project_id)
    joined = false

    if !current_user.nil? && !current_user.projects.nil?
      joined = current_user.projects.include?(@project)
    end

    if joined

      @next_task = @task.next
      @prev_task = @task.prev
      if current_user.completed?(@task)
        redirect_to [@prev_task.project, @prev_task]
      else
        current_user.complete!(@task)
        redirect_to [@prev_task.project, @prev_task]
      end
    else
      flash[:notice] = "Ошибка доступа"
      redirect_to @project
    end
  end

end

app/helpers/task_helper.rb
module TaskHelper
end

app/views/task/show.html.erb
<div class="task-detail">
  <div class="task-detail-menu" style="left: -100%;">
    <div class="text-center">
      <i class="fa fa-times fa-3x icon-btn hidden-lg hidden-md hidden-sm" id="hide-task-menu-btn"></i>
    </div>
    <ul class="list-group">
      <% @tasks.where("header = '1'").order("tag desc").each do |task| %>
          <li class="list-group-item">
            <div class="task-info">
              <p><%= task.title %></p>
              <% $subtaskid = task.tag + 1 %>
              <ul class="list-group">
                <% @tasks.where("tag >= #{$subtaskid}").order("tag desc").each do |task| %>
                  <% if !task.header %>
                    <li id="<%= task.id %>" class="list-group-item <% if current_user.completed?(task) %> task-completed <% end %>">
                        <%= link_to [task.project, task] do %>
                          <span><%= task.title %></span>
                        <% end %>
                        <span class="pull-right">
                          <%= task.timing %>&nbsp;
                          <span id="task_complete_button_<%= task.id %>">
                            <%= render partial: "completed_task/button", locals: {task: task} %>
                          </span>
                        </span>
                    </li>
                  <% else %>
                    <% break %>
                  <% end %>
                <% end %>
              </ul>
            </div>
          </li>
      <% end %>
    </ul>
  </div>

  <div class="task-detail-wrapper hidden-xs" style="z-index: -1; opacity: 0;">
    <i class="fa fa-times fa-3x icon-btn"></i>
  </div>

  <div class="task-detail-content">
    <div class="row">
      <div class="col-lg-1 col-sm-2">
        <i class="fa fa-list-ul fa-2x icon-btn" arid-hidden="true" id="show-task-menu-btn"></i>
      </div>
      <div class="col-lg-11 col-sm-10">
        <h1><%= @task.title %></h1>
        <p>
          <i class="far fa-clock"></i> <span><%= @task.timing %> минут</span>
          <span id="task_status_<%= @task.id %>">
            <% if current_user.completed?(@task) %>
              <span id="task_completed" style="font-size: 12px; margin-left: 10px; padding: 5px 15px; color: white; background-color:#28B62C; border-color: #23a127; border-radius: 5px;">ВЫПОЛНЕНО</span>
            <% else %>
              <span id="task_incompleted" style="font-size: 12px; margin-left: 10px; padding: 5px 15px; color: #555555; background-color:#e2e2e2; border-color: #e2e2e2; border-radius: 5px;">НЕ ВЫПОЛНЕНО</span>
            <% end %>
          </span>
        </p>
      </div>
    </div>
    <br><br>
    <div class="row">
      <div class="col-lg-offset-2 col-lg-8">
        <iframe src="https://player.vimeo.com/video/<%= @task.video %>" width="100%" height="399" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-lg-12 col-md-12 text-center">
        <div class="col-lg-offset-3 col-lg-6 col-md-offset-3 col-md-6">
          <% if !@prev_task.nil? %>
            <div class="col-lg-6 col-md-6">
              <%= link_to prev_path(:id => @task.id), rel: "no-follow" do %>
                <button class="c4s-btn c4s-btn-red">
                  <i class="fas fa-angle-left fa-lg"></i> Предыдущий
                </button>
              <% end %>
            </div>
          <% else %>
            &nbsp;
          <% end %>

          <% if !@next_task.nil? %>
            <div class="col-lg-6 col-md-6">
              <%= link_to next_path(:id => @task.id), rel: "no-follow" do %>
                <button class="c4s-btn c4s-btn-red">
                  Следующий <i class="fas fa-angle-right fa-lg"></i>
                </button>
              <% end %>
            </div>
          <% end %>

        </div>
      </div>
    </div>

    <br>

    <div class="row">
      <div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-12 col-xs-12">
        <div class="task-detail-note">
          <%= markdown(@task.note) %>
          <div id="disqus_thread"></div>
          <script>

          /**
          *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
          *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/

          var disqus_config = function () {
          //this.page.url = '<%= request.fullpath %>';  // Replace PAGE_URL with your page's canonical URL variable
          this.page.identifier = 'task_<%= @task.id %>'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
          };

          (function() { // DON'T EDIT BELOW THIS LINE
          var d = document, s = d.createElement('script');
          s.src = 'https://startup-lessons-ru.disqus.com/embed.js';
          s.setAttribute('data-timestamp', +new Date());
          (d.head || d.body).appendChild(s);
          })();
          </script>
          <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
        </div>
        <br>
      </div>
    </div>

  </div>

</div>

<script>
  $(document).ready(function() {
      // Task detail Page
      // Show/hide Task menu
      $("#show-task-menu-btn").click(function () {
          $(".task-detail-menu").animate({"left": 0}, 300);
          $(".task-detail-wrapper").css({"z-index": 1}).animate({"opacity": 1}, 300);
          $("body").css({"overflow": "hidden"});
      });
      $(".task-detail-wrapper, #hide-task-menu-btn").click(function () {
          $(".task-detail-menu").animate({"left": "-100%"}, 300);
          $(".task-detail-wrapper").animate({"opacity": 0, "z-index": -1}, 300);
          $("body").css({"overflow": "auto"});
      });
      // Scroll by working task
      $(".task-detail-menu").scrollTop($(".task-active").parents(".list-group-item").offset().top - 75);
  });
</script>