config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks' }, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'}

  get 'pages/terms'
  get 'pages/privacy'
  get 'pages/payments'
  get 'pages/about'
  get '/myprojects' => 'project#list'
  get '/pricing' => 'pages#pricing'
  post '/update_card' => 'plan_subscriptions#update_card'
  post '/subscribe' => 'project#subscribe'
  get '/blog' => 'post#index'

  get '/next' => 'task#show_next'
  get '/prev' => 'task#show_prev'

  match '/complete', to: 'completed_task#complete', via: :post
  match '/uncomplete', to: 'completed_task#uncomplete', via: :delete

  root 'project#index'

  resources :project do
    resources :task, only: [:show, :show_next, :show_prev]
  end

  resources :project do
    resources :project_stacks, only: [:show]
  end

  resources :project do
    resources :preview_videos, only: [:show]
  end

  resources :project do
    resources :reviews, only: [:create, :destroy]
  end

  resource :plan_subscriptions
  resources :post
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_devisemes.html.erb
<% unless resource.errors.empty? %>
  <script type="text/javascript">
    <% resource.errors.full_messages.each do |msg| %>
      toastr.error('<%= msg %>')
    <% end %>
  </script>
<% end %>

app/views/shared/_footer.html.erb
<footer class="text-center">
    <%= link_to root_path do %>
      <%= image_tag "logo.png", class: "footer-logo" %>
    <% end %>

    <p>© 2019 ИП Голосниченко А.О. (ИНН 632131078666)</p>
    <div class="footer-links">
      <%= link_to "О компании", pages_about_path %> -
      <%= link_to "Пользовательское соглашение", pages_terms_path %> -
      <%= link_to "Политика конфиденциальности", pages_privacy_path %> -
      <%= link_to "Безопасность платежей", pages_payments_path %>
    </div>
    <p>Свяжитесь с нами <b><a href="mailto:anton@golosnichenko.pro?Subject=Support" target="_top">anton@golosnichenko.pro</a></b></p>

    <div class="footer-social text-center social-buttons">
        <a href="https://twitter.com/StartupLessonRu" target="_blank"><%= image_tag "twitter.png" %></a>
        <a href="https://facebook.com/Startup-Lessonsru-468290447331256/" target="_blank"><%= image_tag "facebook.png" %></a>
        <a href="https://vk.com/startuplessons" target="_blank"><%= image_tag "vk.png" %></a>
        <a href="https://www.youtube.com/channel/UCFaUCYjnQ-nITJROmlKq6lg" target="_blank"><%= image_tag "youtube.png" %></a>
    </div>
</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header hidden-sm hidden-xs">
            <%= link_to "Startup Lessons", root_path, class: "navbar-brand" %>
        </div>

        <ul class="nav navbar-nav navbar-right">

            <li class="hidden-xs"><%= link_to "Блог", blog_path %></li>
            <li class="hidden-xs"><%= link_to "Курсы", root_path %></li>


              <li class="hidden-xs"><%= link_to "Стоимость", pricing_path %></li>
              <% if(!user_signed_in?) %>
                <li class="hidden-xs"><%= link_to "Вход", new_user_session_path %></li>
                <li class="hidden-xs"><%= link_to "Регистрация", new_user_registration_path, class: "c4s-btn c4s-btn-red" %></li>
              <% else %>
                <li class="dropdown hidden-xs">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                        <%= image_tag avatar_url(current_user), :class => "img-circle avatar-medium" %>
                        <%= current_user.name %>
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li><%= link_to "Мои проекты", myprojects_path %></li>
                        <li><%= link_to "Мой профиль", edit_user_registration_path, :"data-turbolinks" => false %></li>
                        <li role="separator" class="divider hidden-xs"></li>
                        <li><%= link_to "Выход", destroy_user_session_path, method: :delete %></li>
                    </ul>
                </li>
              <% end %>

              <div class="row hidden-sm hidden-md hidden-lg">
                  <div class="col-xs-2">
                      <li class="dropdown">
                          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                              <span class="fa fa-list-ul fa-lg"></span>
                          </a>
                          <ul class="dropdown-menu">
                              <li><%= link_to "Блог", blog_path %></li>
                              <li><%= link_to "Курсы", root_path %></li>
                              <li><%= link_to "Стоимость", pricing_path %></li>
                              <% if(!user_signed_in?) %>
                                <li><%= link_to "Вход", new_user_session_path %></li>
                              <% end %>
                          </ul>
                      </li>
                  </div>
                  <div class="col-xs-10">
                    <% if(!user_signed_in?) %>
                      <li><%= link_to "Регистрация", new_user_registration_path, class: "c4s-btn c4s-btn-red" %></li>
                    <% else %>
                    <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                <%= image_tag avatar_url(current_user), :class => "img-circle avatar-medium" %>
                                <%= current_user.name %>
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                              <li><%= link_to "Мои проекты", myprojects_path %></li>
                              <li><%= link_to "Мой профиль", edit_user_registration_path %></li>
                              <li role="separator" class="divider hidden-xs"></li>
                              <li><%= link_to "Выход", destroy_user_session_path, method: :delete %></li>
                            </ul>
                        </li>
                    <% end %>
                  </div>
              </div>


        </ul>
    </div>
</nav>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
    <% flash.each do |type, message| %>
   <%= toastr_flash_class("#{type}") %>('<%= message %>')
 <% end %>
  </script>
<% end %>